### ISSUE TITLE
Custom cancel function as prop feature

### ISSUE THREAD

**Issue by EricSSartorius** [leveluptuts/fresh#10]
It would be nice to use a custom function for the cancel button to do something such as close a modal, not just clear the form

**Comment by stolinski** [comment]
Added new 
```
    case 'resetForm':
      const { defaultValues } = state
      return {
        defaultValues,
        ...state.defaultValues,
      }
```
context action, now called when clicking cancel button

**Comment by stolinski** [comment]
Whoopsies, wrong issue.

**Comment by stolinski** [comment]
Added in 9644720
