### ISSUE TITLE
Remove Styled Components

### ISSUE THREAD

**Issue by stolinski** [leveluptuts/fresh#15]
No need to have it as a dependancy.

**Comment by stolinski** [comment]
Removed in v0.0.14

**Comment by averyfreeman** [comment]
`./node_modules/@leveluptuts/fresh/dist/fresh.esm.js
Module not found: Can't resolve 'styled-components' in '/home/avery/node/react-lessons/fullstack-nextjs/fullstack-course/node_modules/@leveluptuts/fresh/dist'`

Still getting this in 0.1.9 (?)

**Comment by stolinski** [comment]
Go to 0.1.11 Will fix.

**Comment by averyfreeman** [comment]
Thank you :)
