### ISSUE TITLE
Item Prop for model setting of default value

### ISSUE THREAD

**Issue by EricSSartorius** [leveluptuts/fresh#23]
Would be nice to pass custom defaultValues as props to fields in the form

**Comment by stolinski** [comment]
I think you can do that already.

**Comment by stolinski** [comment]
Each field has a defaultValue that gets used in the register field hook, unless I'm misunderstanding this.

**Comment by stolinski** [comment]
I just checked an it's not in the readme. Updating now.

**Comment by stolinski** [comment]
https://github.com/leveluptuts/fresh#common-api---the-props-that-are-common-among-all-fields

feel free to close this if this is what you're looking for.

**Comment by EricSSartorius** [comment]
Naw I guess I worded this wrong, meant to be for the `item` prop

**Comment by stolinski** [comment]
added as defaultValues.
