### ISSUE TITLE
Need to prefer camel case to kebab case when making fields

### ISSUE THREAD

**Issue by EricSSartorius** [leveluptuts/fresh#25]
if i was to have the following:
```
defaultValues = {
videoId: '123'
}
<Form defaultValues={defaultValues} onSubmit={onSubmit} >
  <Field>Video Id</Field>
</Form>
```
the data on submit would consist of both `videoId` and `video-id`.

It would be nice to always have fields default as camelCase instead of kebab to avoid this problem

**Comment by stolinski** [comment]
now live in 0.0.19
