### ISSUE TITLE
Cancel button doesn't work as expected

### ISSUE THREAD

**Issue by EricSSartorius** [leveluptuts/fresh#9]
Pushing 'Cancel' with a fully filled out form only clears the last input in the form, not all of them.

**Comment by stolinski** [comment]
I'll take this one. The functionality has never been added and needs to work with the global state. Right now it wasn't doing anything.

**Comment by stolinski** [comment]
Added new

    case 'resetForm':
      const { defaultValues } = state
      return {
        defaultValues,
        ...state.defaultValues,
      }
context action, now called when clicking cancel button
